### ISSUE TITLE
Publishing Addon

### ISSUE THREAD

**Issue by anilmaurya** [pitchtarget/ember-cli-facebook-js-sdk#1]
This addon was not published. I want to use this addon, therefore I published it (https://www.npmjs.com/package/ember-cli-facebook-js-sdk). Let me know if you have any concern.

**Comment by bugant** [comment]
Thank you @anilmaurya. Yes we would like to publish the addon by ourselves. Please, remove it. We will add it (we were just doing some tests before publishing it).

**Comment by anilmaurya** [comment]
@bugant ok, I will remove it.

**Comment by bugant** [comment]
Thank you @anilmaurya. I'll update the first version today, and then start finishing it up, so that if you want to use it, you can jump start.

**Comment by anilmaurya** [comment]
@bugant I had removed it, go ahead with your publishing.

**Comment by bugant** [comment]
Thank you @anilmaurya, it's up! Enjoy :) Please, let me know any issue you'll find and any feedback you have.

**Comment by anilmaurya** [comment]
Thank you @bugant for writing this but now I am using https://github.com/Vestorly/torii/blob/master/lib/torii/providers/facebook-connect.js .
