### ISSUE TITLE
fb login popup block

### ISSUE THREAD

**Issue by joshuairl** [pitchtarget/ember-cli-facebook-js-sdk#19]
Anybody know how to get the popup blocker to not engage due to the FB.login not being called in response to a direct click?

**Comment by bugant** [comment]
I don't think it's possible. The only solution that comes to mind is to get rid of the Facebook button and perform the login by invoking FB.login from a custom (i.e. normal HTML) button.

**Comment by joshuairl** [comment]
Yikes :(

**Comment by joshuairl** [comment]
So you don't think I can do FB login at all then without it being blocked?
