### ISSUE TITLE
scope at login

### ISSUE THREAD

**Issue by jakope** [pitchtarget/ember-cli-facebook-js-sdk#2]
Hey,
fthank you for your work!

But..
how to use scope like the original FB SDK inside of a controller?

example:
FB.login(function(response) {
   // handle the response
 }, {scope: 'email,user_likes,manage_pages'});

Thank you for your answer,
Greetz jakope

**Comment by bugant** [comment]
@jakope you can use it like that:

```
FB.login('email,user_likes,manage_pages').then(function(response) {
  console.log('success', response);
}).catch(function(reason) {
  console.erorr('error', reason);
});
```

**Comment by jakope** [comment]
Thank you!

Matteo Centenaro <notifications@github.com> schrieb am Fr., 10. Juli 2015
17:50:

**Comment by bugant** [comment]
@jakope I'm closing this issue, if you find any problem feel free to re-open this ticket or create a new one.
