### ISSUE TITLE
Broken import

### ISSUE THREAD

**Issue by jeremytm** [pitchtarget/ember-cli-facebook-js-sdk#3]
I get this when trying to import the addon in an initializer:

```
Uncaught Error: Could not find module `ember-cli-facebook-js-sdk/fb` imported from `rugby-ember/initializers/fb-sdk`
```

**Comment by bugant** [comment]
@jeremytm it's strange. Can you please post a snippet with the relevant code?

**Comment by jeremytm** [comment]
The only code I have changed is straight from your example for the initialiser. It's exactly the same as what is here: https://github.com/bugant/i-have-been-to/blob/master/app/initializers/fb.js

I am using Ember CLI 1.13.8, installed using `npm install ember-cli-facebook-js-sdk --save-dev`

Is this correct?

**Comment by bugant** [comment]
@jeremytm I've just tested with ember-cli 1.13.8 and everything work as expected. I indeed installed the add-on as you did with `npm install ember-cli-facebook-js-sdk --save-dev` and added the initializer, started the serve and had no error.

**Comment by jeremytm** [comment]
My bad, I must not have restarted ember server last time. Oops!

It worked fine this time after restarting. Sorry for wasting your time.
