### ISSUE TITLE
Wrapper style initialization

### ISSUE THREAD

**Issue by ManuelArno** [pitchtarget/ember-cli-facebook-js-sdk#4]
it would be cool to use this library as a wrapper for an already initalized FB raw library.

My usecase is the fb sdk that is injected by torii after successful auth.

**Comment by bugant** [comment]
Hi @ManuelArno, sorry for the delay. For sure, you are right. I think this is a pretty fast change to do. I'll look into it.

**Comment by bugant** [comment]
@ManuelArno, from version `1.0.0` you can now skip the init of the FB sdk.
