### ISSUE TITLE
Chrome on Android reloads the parent page, fails authentication with facebook.

### ISSUE THREAD

**Issue by moha297** [pitchtarget/ember-cli-facebook-js-sdk#9]
When trying to leverage facebook authentication in chrome on Android, the facebook login page opens (as new tab) and my app looses focus. Due to this the chrome seems to be unloading the app from page.

So when you complete the authentication in facebook and try to get your app back in focus it refreshes and looses the javascript state.

I came across a blog post http://www.seanshadmand.com/2015/03/06/facebook-js-login-on-chrome-ios-workaround/ which talks a possible solution for this problem but not the exact scenario I am raising

Which explains a way to overcome this problem.

It does not seem to be happening on phones with better memory and processing power but on the basic android phones.

**Comment by bugant** [comment]
@moha297 this does not seem an issue directly related to this Ember add-on. If so, I would close it. If you, instead, think that it is something related to this project, please provide an example so that we can work on that case.
